version: '3.8'

services:
  backend:
    image: docker.io/thetiptopgrp5/tiptop-backend:latest
    restart: always
    container_name: app-container
    ports:
      - "4001:4001"
    depends_on:
      - db

  frontend:
    image: docker.io/thetiptopgrp5/tiptop-frontend:latest
    restart: always
    container_name: app-prod-container
    ports:
      - "5173:5173"
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./thetiptop_db.sql:/docker-entrypoint-initdb.d/backup.sql
      - postgres_data2:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

volumes:
  postgres_data2:
    driver: local
