version: '3.8'

services:
  backend:
    image: docker.io/thetiptopgrp5/tiptop-backend-dev:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    container_name: app-dev-backend
    ports:
      - "4002:4001"
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: development
    depends_on:
      - db

  frontend:
    image: docker.io/thetiptopgrp5/tiptop-frntend-dev:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    container_name: app-dev-frontend
    ports:
      - "5174:5173"
    environment:
      NODE_ENV: development
    depends_on:
      - backend

  db:
    image: postgres:17
    restart: always
    container_name: postgres-db2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./thetiptop_db.sql:/docker-entrypoint-initdb.d/backup.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
    driver: local

