# Use official Node.js 20 image as base
FROM node:20

# Set the working directory inside the container
WORKDIR /app
COPY . .
RUN yarn install
# Expose port 5173 for the development server
EXPOSE 5173

# Run the application in development mode using 'yarn dev'
CMD ["yarn", "dev"]
